import express, { Request, Response } from "express";
import { lockSystemService } from "../service";
import { LockSystem } from "../model/lock-system.interface";
import { requireAdmin, requireAuth } from "./auth";

/** Routes for listing and creating lock systems. */
export const lockSystemRouter = express.Router();

/**
 * `GET /lock-systems` — lists the lock systems visible to the logged-in
 * user: every system for admins, assigned systems only for regular users.
 *
 * Responses: 200 with the systems, 401 if not logged in.
 */
lockSystemRouter.get(
  "/",
  async (req: Request, res: Response<LockSystem[] | string>) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;

      const assignedIds =
        user.role === "admin" ? ("ALL" as const) : user.assignedLockSystemIds;
      const systems = await lockSystemService.getVisibleForUser(assignedIds);
      res.status(200).send(systems);
    } catch (e: any) {
      res.status(500).send(e.message);
    }
  },
);

/**
 * `GET /lock-systems/:referenceCode` — returns one lock system by its
 * reference code (e.g. "SYS-001"). Requires a logged-in user.
 *
 * Responses: 200 with the system, 401 if not logged in, 404 if no system
 * has that reference code.
 */
lockSystemRouter.get(
  "/:referenceCode",
  async (
    req: Request<{ referenceCode: string }>,
    res: Response<LockSystem | string>,
  ) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;

      const system = await lockSystemService.getByReferenceCode(
        req.params.referenceCode,
      );
      if (!system) {
        res.status(404).send("Lock system not found");
        return;
      }
      res.status(200).send(system);
    } catch (e: any) {
      res.status(500).send(e.message);
    }
  },
);

/**
 * `POST /lock-systems` — creates a new lock system. Admin only.
 *
 * Body: `{ name: string, description: string }`. The reference code is
 * generated by the service.
 *
 * Responses: 201 with the created system, 400 if a field is invalid,
 * 401/403 if not logged in as an admin.
 */
lockSystemRouter.post(
  "/",
  async (
    req: Request<{}, {}, { name: string; description: string }>,
    res: Response<LockSystem | string>,
  ) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;

      const { name, description } = req.body;

      if (typeof name !== "string" || typeof description !== "string") {
        res.status(400).send("Fields 'name' and 'description' must be strings");
        return;
      }

      const created = await lockSystemService.addLockSystem(name, description);
      res.status(201).send(created);
    } catch (e: any) {
      res.status(500).send(e.message);
    }
  },
);
